name: Node.js CI

on:
  push:
    branches: ["main"]

env:
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set lowercase repository owner
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Test with ESLint
        run: npm run lint

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/nodejs-ci-lab:latest
            ghcr.io/${{ env.OWNER_LC }}/nodejs-ci-lab:${{ github.sha }}
